services:
    langgraph-redis:
        image: redis:alpine
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5

    langgraph-api:
        image: "agenthub:latest"
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            POSTGRES_URI: postgresql://postgres.lcnkzptzirdcvemvbjan:GMRjt41fMuDShNoV@aws-0-us-west-1.pooler.supabase.com:5432/postgres
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            LANGSMITH_ENDPOINT: ${LANGSMITH_ENDPOINT}
            LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
            LANGSMITH_TRACING: ${LANGSMITH_TRACING}
        extra_hosts:
            - "host.docker.internal:host-gateway"
            

